// Normally generated by `wrangler types`; hand-written here since this
// worker's bindings are simple (one Durable Object, no R2/KV yet).
interface Env {
  TLDRAW_DURABLE_OBJECT: DurableObjectNamespace;
}
